logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    org.mongodb.driver: WARN
    com.aaryadewa.rnd.simpanpinjam: DEBUG

spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true
  jackson:
    serialization:
      indent-output: true
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: simpanpinjam
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5435/simpanpinjam
    username: simpanpinjam
    password:
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      hibernate.format_sql: true
      hibernate.generate_statistics: true
      hibernate.javax.cache.missing_cache_strategy: create
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080

# application:
